# Generated by Django 4.1.2 on 2022-10-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_rename_seats_available_event_seats"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Event",
            new_name="Events",
        ),
    ]
