# Generated by Django 4.1.2 on 2022-10-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_rename_event_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="")),
                ("organizer", models.CharField(max_length=30)),
                ("seats", models.PositiveIntegerField(default=0)),
                ("price", models.CharField(blank=True, default="", max_length=30)),
                ("seats_booked", models.PositiveIntegerField(default=0)),
                ("date_event", models.DateField()),
                ("date_created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Events",
        ),
    ]
